### ISSUE TITLE
[Bug] Background transparency using lualine.

### ISSUE THREAD

**Issue by NikoKS** [vimpostor/vim-tpipeline#21] opened 2022-01-21 11:42 UTC
First of all, lots of praise for this plugin. Absolutely achieving things I thought were not possible before.

I'm trying to achieve a transparent look using tpipeline and lualine. Following this [reddit post](https://www.reddit.com/r/neovim/comments/s4ud1d/make_lualine_background_transparent/), I was able to achieve that and the background transparency even carry over when using tmux. But for some reason, It loses all foreground color when inside tmux as seen in the screenshot below:

Outside tmux:
![Screen Shot 2022-01-21 at 18 40 31](https://user-images.githubusercontent.com/24285511/150521260-6ec99f40-c9ce-4d87-b2b9-9059e8074717.png)

Inside tmux:
![Screen Shot 2022-01-21 at 18 41 15](https://user-images.githubusercontent.com/24285511/150521279-3efe5057-308f-4a2b-b688-dfa16e53c5c9.png)

As can be seen, transparency persist, but the green and blue colors went away. I was wondering if this is something that could be fixed. Unfortunately, I am unable to diagnose the root cause of this.

**Comment by vimpostor** [comment] 2022-01-21 11:52
Try using `let g:tpipeline_fillcentre = 1`.

If this doesn't work, please attach your vim config (or the relevant 
part of your config), as I am failing to understand what exactly you 
mean with background transparency. I can see the difference in your 
screenshot, but I don't quite get where the orange background inside 
tmux comes from.

Maybe this is also a case of using `let g:tpipeline_preservebg = 1`, but 
I need to be able to reproduce to be sure.

**Comment by NikoKS** [comment] 2022-01-21 14:03
Thanks for the response! Let me get the minimum config to reproduce it.

The orange background just came from my desktop background. I use iTerm and set the window to be more transparent just to contrast the difference.

**Comment by vimpostor** [comment] 2022-01-21 19:53
Hey thanks for trying to find a minimal reproducable example for me, I appreciate it, but unfortunately it is too minimal:

> hmm.. somehow just having a single line in my config is enough to recreate the issue outside tmux

Yes because then you are missing one of the key requirements for this plugin to work:

> # Requirements
> - True color support

The default neovim colorscheme does not have true color support, therefore the colors that lualine will use will not comply with what tpipeline requires.

However, pretty much every single colorscheme out there has true color support, so it should work with your normal config.
It's okay for you to just paste your entire config, I think that's easier for me to reproduce than just iteratively keep asking for more parts of your config.

**Comment by NikoKS** [comment] 2022-01-24 09:31
My normal config might be a bit unconventional to read since I'm using [LunarVim](https://github.com/LunarVim/LunarVim). But [here](https://github.com/NikoKS/dots/tree/dev/dotfiles/lvim) it is if you're interested.

I'll work on some more debugging, probably by uninstalling LunarVim first when I have the time. But feel free to close this issue for now If it's bugging you that there's an open issue.

**Comment by vimpostor** [comment] 2022-01-24 17:52
> But feel free to close this issue for now If it's bugging you that there's an open issue.

Absolutely not, you are doing me a favor by reporting issues. If someone starts ignoring issues, it does not make the software better.

I still have trouble understanding what exactly to reproduce here, especially since I don't use a transparent terminal.
I have added some debug info to the plugin just now, would you mind posting me the output of the following while you are experiencing the problem inside tmux:
```vim
:echom tpipeline#debug#debug_info()
```

**Comment by NikoKS** [comment] 2022-01-27 02:46
Hi, here is the output from the new command:
```
{'right': ['#[fg=,bg=#NONE]#[fg=#bf616a,bg=#NONE]  2 #[fg=,bg=#NONE]#[fg=#98be65,bg=#NONE]    #[fg=,bg=#NONE]#[fg=,bg=#NONE,bold] [pyright] #[fg=,bg=#NONE,nobold]#[fg=,bg=#NONE]#[fg=#357
2a5,bg=#NONE] #[fg=,bg=#NONE] python #[fg=,bg=#NONE,bold]  25:1  '], 'native_str': '   BA-4183  monitor.py    4 柳5  1
                 2      [pyright]   python   25:1  ', 'left': ['#[fg=,bg=#NONE,bold]   BA-4183 #[fg=,bg=#NONE,nobold]#[fg=,bg=#NONE] monitor.py #[fg=,bg=#NONE]#[fg=#a3be8c,bg=#NONE]  
 4 #[fg=#ebcb8b,bg=#NONE]柳5 #[fg=#bf616a,bg=#NONE] 1 #[fg=,bg=#NONE]'], 'native_highlights': [{'group': 'lualine_b_3_normal', 'start': 0}, {'group': 'lualine_b_normal', 'start': 14}, {'g
roup': 'lualine_b_filename_normal', 'start': 14}, {'group': 'lualine_c_diff_normal', 'start': 26}, {'group': 'lualine_c_diff_added_normal', 'start': 26}, {'group': 'lualine_c_diff_modified
_normal', 'start': 34}, {'group': 'lualine_c_diff_removed_normal', 'start': 39}, {'group': 'lualine_c_normal', 'start': 45}, {'group': 'lualine_x_diagnostics_normal', 'start': 125}, {'grou
p': 'lualine_x_diagnostics_error_normal', 'start': 125}, {'group': 'lualine_c_normal', 'start': 132}, {'group': 'lualine_x_6_normal', 'start': 132}, {'group': 'lualine_c_normal', 'start':
139}, {'group': 'lualine_x_7_normal', 'start': 139}, {'group': 'lualine_c_normal', 'start': 150}, {'group': 'lualine_x_filetype_normal', 'start': 150}, {'group': 'lualine_x_DevIconPy_norma
l', 'start': 150}, {'group': 'lualine_c_normal', 'start': 154}, {'group': 'lualine_a_normal', 'start': 162}]}
```
I hope that would help

**Comment by vimpostor** [comment] 2022-01-27 19:11
Whoops, looks like there was indeed a bug in the color translation, thanks for the help.
It should be fixed now.

**Comment by NikoKS** [comment] 2022-01-30 06:50
Hey, thank you very much for the fix!

The bad news is that the new commits still have not fixed the issue.
The good news is that to fix it, you just need to add an extra `|| bg ==# '#NONE'` to the if condition.

Could you help add those to the fix?
Thank you again!

**Comment by vimpostor** [comment] 2022-01-30 09:58
Wow thanks for debugging this. However are you sure you are using the latest version already, I added a similar check in e0228afde21f194147f4a20fcb42ea170464ceef. But if you are using the latest version already, I would be happy to accept your pull request. :)

In that case you can just replace the condition I added in e0228afde21f194147f4a20fcb42ea170464ceef with your fixed condition. It would be interesting though where this `'#NONE'` comes from, do you have any idea about what highlight command I have to use to create such a color?

For example if I do the following:
```vim
hi Transparent guifg=#ffffff guibg=NONE
let id = synIDtrans(hlID('Transparent'))
```

Then `echom synIDattr(id, 'bg')` returns `''` and not `#NONE`.

**Comment by vimpostor** [comment] 2022-01-30 21:19
> Could you help add those to the fix?

Sry I misunderstood you earlier, I thought you wanted to make a PR.
I have now added your proposed fix.

**Closed by vimpostor** 2022-01-30 21:19 UTC

**Comment by NikoKS** [comment] 2022-01-31 01:53
Thank you for the fix, it now works beautifully!.

> Then echom synIDattr(id, 'bg') returns '' and not #NONE.

Hmm, I think '#NONE' might be a bug with lualine. but for now this fix works well.
